# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_RK628_MISC) += rk628.o rk628_cru.o rk628_config.o rk628_post_process.o rk628_combrxphy.o rk628_hdmirx.o rk628_combtxphy.o rk628_dsi.o panel.o rk628_lvds.o rk628_rgb.o rk628_gvi.o rk628_pinctrl.o \
	 rk628_csi.o rk628_efuse.o
obj-$(CONFIG_DRM) += rk628_hdmitx.o
